### ISSUE TITLE
What is compute_actev_world_norm.py

### ISSUE THREAD

**Issue by isaryo** [JunweiLiang/Multiverse#10]
Hi.I have a question.
I read [this line](https://github.com/JunweiLiang/Multiverse/blob/9213b14f2bf35eeba9a33ac2a5c0946f8190a0e2/forking_paths_dataset/code/plot_traj_carla.py#L77) and search compute_actev_world_norm.py.
But I could not be found compute_actev_world_norm.py.
Where is compute_actev_world_norm.py?
Also What was your calculation process in getting carla world coordinates?

**Comment by JunweiLiang** [comment]
Please follow the tutorial [here](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#step-2-get-the-appropriate-calibration-parameters-origin-rotation-etc-to-convert-trajectories-into-carla-map-specific-coordinates) about getting the world coordinates in CARLA. If you have specific questions about the tutorial you can list them here. `compute_actev_world_norm.py` is not provided. As the [comments](https://github.com/JunweiLiang/Multiverse/blob/master/forking_paths_dataset/code/plot_traj_carla.py#L78) say, the `actev_norm` just includes the min and max of the coordinates in each scene.

**Comment by isaryo** [comment]
I have one more thing to ask. I'm try to make a new dataset like the forking path.
How do you get the calibration parameters?
And please let me know a formula how to convert trajectories into CARLA world coordinates?

**Comment by JunweiLiang** [comment]
Hi,
The calibration parameters (just the homography matrics) are provided in ETH/UCY/ActEV. For new videos, you can manually calibrate them with this [code](https://github.com/zhengthomastang/Cal_PnP) or this [code](https://github.com/lishengzhe/ccvs) or automatically with this [paper](https://arxiv.org/abs/1905.02231). It is a classic computer vision problem. 
You can follow the tutorial - "[Recreate Scenarios from Real World Videos](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#recreate-scenarios-from-real-world-videos)" to recreate a new dataset. Converting trajectories from 2D view to 3D world involves knowing the basic [pin-hole camera model](https://en.wikipedia.org/wiki/Pinhole_camera). Go through the tutorial and related code and you'll understand.

**Comment by abhi-rf** [comment]
Hi,

@JunweiLiang 
First of all, thanks for the lovely repo.
Could you also tell how can we get the world coordinates from the pixel coordinates for the trajectories esp for the birds eye view ?

Regards
Abhishek

**Comment by JunweiLiang** [comment]
Converting coordinates from pixel to world (2D to 3D) needs the depth map. If by "world coordinates" you mean ground-plane coordinates the problem becomes 2D to 2D coordinates transformation. Then you only need the 3x3 homography matrix. We get these world ground-plane coordinates for ETH/UCY/ActEV using their provided homography matrices.

**Comment by abhi-rf** [comment]
Hi,

Thanks for the reply. Also, if I want to plot certain trajectories in the unprepared data for some scene, how do I convert the b-box coordinates to the x,y coordinate (without changing the space of reference)?

**Comment by JunweiLiang** [comment]
x, y coordinates on the ground plane? Then you'll need the homography matrix between the camera view and the ground plane of the unseen scene.

**Comment by abhi-rf** [comment]
> 
> 
> x, y coordinates on the ground plane? Then you'll need the homography matrix between the camera view and the ground plane of the unseen scene.

No, I mean I am trying one of the forking paths scene of the form 0000_x_300_... (I mean not the eth/zara etc). So how do I get the coordinates from the bounding box(found from the json)!

**Comment by JunweiLiang** [comment]
Camera parameters are in the [code](https://github.com/JunweiLiang/Multiverse/blob/master/forking_paths_dataset/code/utils.py#L176). You can get the world coordinates from the `actev_candidates_m15.2_skip10` folder, and visualize them according to [Step 4](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#step-4-manually-check-the-filtered-scenarios-and-prepare-for-multi-future-annotations) of the tutorial.

**Comment by dendorferpatrick** [comment]
I am also having problems getting the scaling of the trajectories. I am working on the top-down camera videos. Where can I find the scaling factor that transforms one pixel into the corresponding length in meters?

**Comment by JunweiLiang** [comment]
The units in CARLA  (transform) are actually in meters (see [here](https://carla.readthedocs.io/en/stable/measurements/)). So the l2 norm of the world coordinates is in meters. As I mentioned previously, get the world coordinates by using the camera parameters in the [code](https://github.com/JunweiLiang/Multiverse/blob/master/forking_paths_dataset/code/utils.py#L176) or get the world coordinates from the `actev_candidates_m15.2_skip10` folder.
