### ISSUE TITLE
SimAug dataset video files name

### ISSUE THREAD

**Issue by Explorerhpx** [JunweiLiang/Multiverse#11]
Hi, Thanks for your contribution!
I just want to make sure that the files of SimAug Dataset are named with the following format:
VIRAT_S_[4-digit scene id][xx]\_[2-digit moment id]\_[moment start time]\_[moment end time]\_F\_[frame id]_obs12\_pred16\_[camera id]

**Comment by JunweiLiang** [comment]
No. The file name in SimAug dataset is very different from the ForkingPaths dataset.
Example: VIRAT_S_040000_03_000221_000372_F_1879_obs12_pred16_cam1.mp4
everything before "_F_" is the video filename from the original VIRAT dataset, i.e., [videoname]_F_[frame_idx]_obs12_pred16_cam[camera_idx, 1-4]
