### ISSUE TITLE
How to apply the model to predict the trajectory in a new video

### ISSUE THREAD

**Issue by hxy-tech** [JunweiLiang/Multiverse#13]
Hello, how do you need to apply your code to predict the trajectory in a new video? In other words, where to put the video and what code to run? Thanks for your answer
您好，请问如果要应用您的代码预测一个新的视频中的轨迹，需要怎样具体操作呢？也就是说将该视频放在哪里以及运行哪些代码呢？谢谢您的回答

**Comment by hxy-tech** [comment]
Hello, how do you need to apply your code to predict the trajectory in a new video? In other words, where to put the video and what code to run? Thanks for your answer  How to apply the model to predict the trajectory in a new video?

**Comment by JunweiLiang** [comment]
Given a new video dataset, you will need to prepare the data and features in the format [this repo](https://github.com/JunweiLiang/Multiverse/blob/master/TESTING.md#step-1-preprocess) requires (it is also similar to the [Next model repo](https://github.com/google/next-prediction/blob/master/TESTING.md#step-2-preprocess---actev)). Then you can follow the steps in the inference and [visualization](https://github.com/JunweiLiang/Multiverse/blob/master/TESTING.md#visualization).
To prepare the data and features, follow this [instruction](https://github.com/google/next-prediction#preparing-rich-visual-features) from the Next repo.
