### ISSUE TITLE
Data : How to generate pedestrian to scene feature mapping?

### ISSUE THREAD

**Issue by AnuragKatakkar** [JunweiLiang/Multiverse#15]
Hi, we are trying to generate scene features for the ActEV/VIRAT dataset. How does one get mapping from pedestrian id to scene features?

Also, what do the various parts of the tray_key  "VIRAT_S_000005_1584_0" correspond to?

**Comment by JunweiLiang** [comment]
Could you provide more information? Which data file do you refer to?

The traj_key in multiverse can be interpreted according to [here](https://github.com/JunweiLiang/Multiverse/blob/master/code/multifuture_inference.py#L185).

For scene feature processing, we first compute the correct scene grid used in the models based on the number of convolutions we used and the original scene feature sizes. (see [here](https://github.com/JunweiLiang/Multiverse/blob/master/code/preprocess.py#L90)). Then we map the correct whole scene feature frame to each pedestrian (see [here](https://github.com/JunweiLiang/Multiverse/blob/master/code/preprocess.py#L374)). At run time, we apply convolution on top of the original scene features (see [here](https://github.com/JunweiLiang/Multiverse/blob/master/code/pred_models.py#L157)) and then apply the one-hot location mask of each pedestrian at each time-step to get the features (see [here](https://github.com/JunweiLiang/Multiverse/blob/master/code/pred_models.py#L210)).

**Comment by JunweiLiang** [comment]
Does the above answer your questions?
