### ISSUE TITLE
SDD data split for simaug

### ISSUE THREAD

**Issue by nachiket92** [JunweiLiang/Multiverse#16]
Hi, congratulations on the paper and thank you for sharing the code!

I had a  question regarding the SDD data split shared here and reported in the SimAug paper. I'm working on a related model -- I'm one of the authors of P2T_IRL which was a baseline considered in the paper. I wanted to make sure we're using the same data split for a fair comparison.

The data splits shared here: https://next.cs.cmu.edu/data/sdd_data_splits_eccv2020.tgz
seem to be a random 5-fold split of the videos. However baselines reported in the paper (SoPhie, SocialGAN, P2T_IRL) as well as others (MATF-GAN, CF-VAE) have reported results for a very specific train, val and test split of SDD which corresponds to the scenes in the TrajNet benchmark. 

Do the numbers reported for SimAug in table 2 (a) correspond to the same split as used by the baselines? 

Thanks again!

-- Nachiket

**Comment by JunweiLiang** [comment]
Random split is used in the paper. We take the numbers from the SoPhie paper, which is unclear what "standard split" they refer to.

**Comment by nachiket92** [comment]
Thank you for the response. I had contacted the authors of the SoPhie paper. They have used a data split corresponding to scenes in the [TrajNet benchmark.](http://trajnet.stanford.edu/).The train/val/test scenes are listed in Table 1 of the P2T_IRL paper.

I believe the same split ought to be used for a fair comparison, since other works (including baselines reported) have used this split.

**Comment by nachiket92** [comment]
Sorry to keep pushing this issue, but there's another detail: It seems only pedestrians were considered (based on line 129 of 'get_prepared_data_sdd.py'), whereas prior work from table 2(a) has considered other agents as well (skaters, bikers, golf carts etc.).  

In any case, I really admire the work, and appreciate that the code was shared.

**Comment by JunweiLiang** [comment]
Yes, you are right. In VIRAT/ActEV, people on bikes or skateboards are still labeled "People". Will add a note to the repo.
