### ISSUE TITLE
Can't cook the maps

### ISSUE THREAD

**Issue by isaryo** [JunweiLiang/Multiverse#17]
Hi.
I use UE 4.22.3 according to [this guide](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#edit-the-maps).But I received the following error message．

Increasing per-process limit of core file size to infinity.
Project file not found: carla_source_09272019/Unreal/CarlaUE4/CarlaUE4.uprojectPreparing to exit.Shutting down and abandoning module NetworkFile (12)Shutting down and abandoning module CookedIterativeFile (10)Shutting down and abandoning module StreamingFile (8)Shutting down and abandoning module SandboxFile (6)Shutting down and abandoning module PakFile (4)Shutting down and abandoning module RSA (3)Exiting.Exiting abnormally (error code: 1)
FGlobalDynamicReadBuffer::Cleanup()FGlobalDynamicReadBuffer::Cleanup

Do you have any solutions?

**Comment by JunweiLiang** [comment]
After which step did you receive this error message? It seems that your carla source path is not named "carla_source_09272019". Follow [this](carla_source_09272019/) to download maps to the right path first.

**Comment by isaryo** [comment]
Sorry. Where should I refer to [this](https://github.com/JunweiLiang/Multiverse/issues/carla_source_09272019/)?

**Comment by JunweiLiang** [comment]
Oops. Updated the link.

**Comment by isaryo** [comment]
I tried to edit the maps referring to [this](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#edit-the-maps).
I used [this](https://drive.google.com/file/d/18zIMtWpmaq4nYHpdrTxNPFwE7EgK13qU/view) for carla.
Then I received error message.

**Comment by JunweiLiang** [comment]
Does `carla_source_09272019/Unreal/CarlaUE4/CarlaUE4.uproject` exist in the folder? It should be. Your error message says it is not.

**Comment by isaryo** [comment]
It does exist.
I haven't touched [it](https://drive.google.com/file/d/18zIMtWpmaq4nYHpdrTxNPFwE7EgK13qU/view) since I downloaded it.

**Comment by JunweiLiang** [comment]
Could you first start with [this step](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#step-1-prepare-and-test-the-carla-simulator) and see whether you can successfully start a CARLA server and a spectator window? Then follow [this step](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#edit-the-maps) to download Carla 0.9.6 from the official website and install it.
