### ISSUE TITLE
Can it predict the path of a pedestrian in a video in real time?

### ISSUE THREAD

**Issue by Taraing** [JunweiLiang/Multiverse#20]
Thanks for your excellent work.I am a beginner in this field.I have detect people by yoloV5 with my computer camera,I want to know whether i can use the SimAug to predict the people's trajectory directly?If can,whether i should preproccess my video?

**Comment by JunweiLiang** [comment]
Sure! I used [this](https://github.com/JunweiLiang/Object_Detection_Tracking) object detection and tracking repo and built an end-to-end trajectory prediction [system](https://github.com/JunweiLiang/social-distancing-prediction). It achieved real-time on a GTX 1080 TI GPU (the prediction model is the [Next](https://github.com/google/next-prediction) model).

**Comment by JunweiLiang** [comment]
You will need to take a look into the code of the end-to-end system [here](https://github.com/JunweiLiang/social-distancing-prediction) and replace the model with the SimAug model and make necessary changes to the code.

**Comment by 108618026** [comment]
@JunweiLiang 
Is it possible to show FPS? 
Like the image below.
Thanks in advanced!
![image](https://user-images.githubusercontent.com/65159089/189137911-de0f4caa-8099-4e77-b737-cf2ec88ce34d.png)
