### ISSUE TITLE
Visualize the model output

### ISSUE THREAD

**Issue by HITjian** [JunweiLiang/Multiverse#24]
Hello
when I run your code '' vis_multifuture_trajs_video.py'' ,there happened  the follow problem:
 File "code/vis_multifuture_trajs_video.py", line 85, in <module>
    raise Exception("Cannot open %s" % video_file)
Exception: Cannot open forking_paths_dataset/multifuture_visualization/0400_50_293_cam4.mp4

I have generated the multi-future videos , but it seems not complete（there are just 9 viodes not including 0400_50_293_cam4.mp4）.
So could you please tell me what's wrong with it?
Look forward to your reply， thank you!

**Comment by JunweiLiang** [comment]
This means something went wrong when generating the multi-future videos in this [step](https://github.com/JunweiLiang/Multiverse/blob/master/forking_paths_dataset/README.md#visualize-the-dataset). Please redo the prepare data and visualization steps [here](https://github.com/JunweiLiang/Multiverse/blob/master/forking_paths_dataset/README.md). The videos in `next_x_v1_dataset/rgb_videos/` should be 3000 and the multifuture visualization videos should be 507.

**Comment by HITjian** [comment]
Thanks for your reply! I will try it again!
