### ISSUE TITLE
Feeding more features into forking path dataset

### ISSUE THREAD

**Issue by Jacobieee** [JunweiLiang/Multiverse#25]
Hi, I currently want to use the bounding box extracted in pickles files and feed them into the model when doing multifuture inference in multifuture_inference.py and I am not sure I understand the preprocess correctly. I noticed that in Virat preprocess, you stored every other box coordinates for each person in each frame. Thus, for data["other_box"] in each data sample, there is an array of lengths 8 which contains coordinates of other boxes at each time. 

But for the forking path dataset, I only need to process the other box feature for the "controlled agent", right? So, the final processed other_box will be [N, obs_len, K] where K is the number of other boxes and N is 507, the number of the testing set. 

Thanks for that.

**Comment by JunweiLiang** [comment]
The statement about VIRAT preprocess is correct. For the forking path dataset, there are 507 test samples so yes the other_box should be [507, obs_len, K, 4]
