### ISSUE TITLE
How to visualize new videos in simaug project？

### ISSUE THREAD

**Issue by CAOXINGWEN** [JunweiLiang/Multiverse#26]
My question is, how can the SimAug project be applied to the new video？I looked at your  code, and you visualized the SDD campus dataset and the argoverse dataset. When I was viewing the SimAug project, you visualized the SDD dataset in the **prepro.md** file. There is a line of command written like this:
`python code/get_prepared_data_sdd.py annotations/ data_splits/fold_1 resized.lst prepared_data_fold1`
There are annotations in the SDD dataset. If I take a new video to test, do I also need annotations annotation files?
Thank you very much.

**Comment by JunweiLiang** [comment]
We did not provide visualization instructions for new videos in this repo. Check out this [repo](https://github.com/JunweiLiang/social-distancing-prediction) to run trajectory prediction on any videos.
