### ISSUE TITLE
Creating Whole Garden of forking path dataset as single future

### ISSUE THREAD

**Issue by rameezrehman83** [JunweiLiang/Multiverse#28]
Thank you for your reply.

I have a few more confusions and questions regarding this work.

In Paper, Table 3, Is the “Trained on simulation” column trained on whole simulated data (created with get_prepared_data.py and then extracting frames and scenes)?

I am trying to create the whole dataset for training but by using get_prepared_data.py and then using get_frames_and_scene_seg.py, I get about 224 warnings (bad videos). For example: warning, 0401_67_204_1_12_cam3 video has 30 rgb frame, 30 seg frames, 31 in traj. If i change  “while cur_rgb_frame < frame_count:”  to  “while cur_rgb_frame < =frame_count:” I get assert error “assert suc, (videoname, cur_rgb_frame, frame_count)” because there is no frame  at while cur_rgb_frame =frame_count.

In get_prepared_data.py the drop frame is always drop_frame = args.drop_frame["virat"] which is equal to 12. Should i also add drop_frame = args.drop_frame["ethucy"], the way you do in  get_prepared_data_multifuture.py??

_Originally posted by @rameezrehman83 in https://github.com/JunweiLiang/Multiverse/issues/27#issuecomment-920171760_

**Comment by JunweiLiang** [comment]
The "trained on simulation" experiment refers to the model trained on "anchor videos", which were reconstructed from the real-world ActEV videos. See [here](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#step-3-run-simulations-to-remove-scenarios-with-collisions). 
Please follow the training instructions from [here](https://github.com/JunweiLiang/Multiverse/blob/master/TRAINING.md) to reproduce the main experiments if that's what you want.

**Comment by rameezrehman83** [comment]
Thank you for your reply. I want to reproduce the results with "anchor videos". I got a question regarding the preprocessing of "anchor videos". How do you use the "anno_scene" for "anchor videos" as I don't get them after running "get_prepared_data.py". In in "get_prepared_data.py" line 71,72, "anno_scene" is mentioned but is commented:  
# we will have scene segmentation feature for each needed frame
#args.scene_map_path = os.path.join(args.outpath, "anno_scene")
Can you please comment on how to get "anno_scene" for anchor_videos. Thank you

**Comment by JunweiLiang** [comment]
I have not prepared the instructions for "anchor videos" experiment for the CVPR 2020 paper. Could you look at the instructions from [here](https://github.com/JunweiLiang/Multiverse/blob/master/SimAug/TRAINING.md#simaug-training), which is in the ECCV'20 paper where we do training with multi-view anchor videos, and see whether that could help you first? Thanks.
