### ISSUE TITLE
How to visualize Actev datasets in Simaug?

### ISSUE THREAD

**Issue by CAOXINGWEN** [JunweiLiang/Multiverse#29]
hi,Thank you for your work.I see you provide a visual flow of  sdd and argoverse datasets in
PREPRO.md, but did not provide the process of actev dataset. Can you tell me how to visualize,I think there are both get_prepared_data_sdd.py and get_prepared_data_argoverse.py Python files.

**Comment by JunweiLiang** [comment]
For the preprocess of ActEV dataset, we follow the ones in the [Next](https://github.com/google/next-prediction#preparing-rich-visual-features) paper. For visualizing ActEV dataset, you can check out this [issue](https://github.com/google/next-prediction/issues/4).
