### ISSUE TITLE
0000_11_346_0_12_cam2 is skipped when preparing data

### ISSUE THREAD

**Issue by Mzunoven** [JunweiLiang/Multiverse#3]
I'm trying to run the test session of this repo, but I noticed that there is a warning that **0000_11_346_0_12_cam2 is skipped due to bad x_agent boxes** when preparing data and thus this video cannot be visualized in the multi-future part.

Can you help in solving this problem?

**Comment by JunweiLiang** [comment]
Yeah that is expected. So the current version of the test set is 2999 videos. I may solve this in the future if we are going to have a larger dataset.
