### ISSUE TITLE
How to run model on one test video ?

### ISSUE THREAD

**Issue by MostafaAlemam** [JunweiLiang/Multiverse#30]
Hello,
I just want to run the model to predict the output of one test video from the forking path dataset as I don't want to extract seg frames and RGB frames every time as it takes too long.

**Comment by JunweiLiang** [comment]
Hi, 
This repo is for reproducing the results in the paper. For a end-to-end solution, take a look at this [project](https://github.com/JunweiLiang/social-distancing-prediction), which uses our [CVPR'19](https://github.com/google/next-prediction) prediction models.
