### ISSUE TITLE
Where is deeplabv3 loacate?

### ISSUE THREAD

**Issue by 108618026** [JunweiLiang/Multiverse#33]
Excuse me! @JunweiLiang 

Could you tell me where does deeplabv3_xception_ade20k_train/frozen_inference_graph.pb locate?
I can't find it.

Thanks in advance!

**Comment by JunweiLiang** [comment]
It's from [Deeplab](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md)'s model zoo [here](http://download.tensorflow.org/models/deeplabv3_xception_ade20k_train_2018_05_29.tar.gz) (xception ADE20K trained model).
