### ISSUE TITLE
Visualize semantic segmentation image?

### ISSUE THREAD

**Issue by 108618026** [JunweiLiang/Multiverse#34]
Excuse me! @JunweiLiang 

When I run the following code, the files' extention in scene_seg_36x64_argoverse folder is NPY. Would it be possible to visualize the semantic segmentation feature.

Like this! ![image](https://user-images.githubusercontent.com/65159089/173527851-c2517c22-0be2-452e-83b9-0147a429634c.png)

Thanks in advanced!

python code/extract_scene_seg.py val_frames_renamed.lst ^
deeplabv3_xception_ade20k_train/frozen_inference_graph.pb ^
scene_seg_36x64_argoverse --every 1 --down_rate 8.0 --job 1 --gpuid 0 --save_two_level

**Comment by JunweiLiang** [comment]
No, this repo does not provide this code. But a simple Google search could definitely help you. The NPY is a matrix of (H, W) and each item is the scene class.
