### ISSUE TITLE
Pretrained model can't download!!

### ISSUE THREAD

**Issue by 108618026** [JunweiLiang/Multiverse#35]
Excuse me! @JunweiLiang 

When I ran the command  (bash scripts/download_single_models.sh), it seems like it can't download the pretrain model in multiverse.

download_single_models.sh: line 2: $'\r': command not found
--2022-07-02 09:32:26--  https://next.cs.cmu.edu/multiverse/dataset/multiverse-models.tgz%0D
Resolving next.cs.cmu.edu (next.cs.cmu.edu)... 128.2.220.9
Connecting to next.cs.cmu.edu (next.cs.cmu.edu)|128.2.220.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-02 09:32:26 ERROR 404: Not Found.

download_single_models.sh: line 4: $'\r': command not found
tar (child): multiverse-models.tgz\r: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Thanks in advanced!

**Comment by JunweiLiang** [comment]
I'm guessing it is a Windows issue (the \r problem). This command is tested under Ubuntu. You can reach the [link](https://next.cs.cmu.edu/multiverse/dataset/multiverse-models.tgz) by opening it in the browser.
