### ISSUE TITLE
Reason why no use_gnn in Multimodal testing

### ISSUE THREAD

**Issue by HRHLALALA** [JunweiLiang/Multiverse#37]
Hello, I notice that you did not use GAT during the multimodal testing. May I ask the reason behind that? 

```
python code/multifuture_inference.py forking_paths_dataset/next_x_v1_dataset_prepared_data/obs_data/traj_2.5fps/test/ \
forking_paths_dataset/next_x_v1_dataset_prepared_data/multifuture/test/ \
multiverse-models/multiverse_single18.51_multi168.9_nll2.6/00/best/ \
model1_output.traj.p --save_prob_file model1_output.prob.p \
--obs_len 8 --emb_size 32 --enc_hidden_size 256 --dec_hidden_size 256 \
--use_scene_enc --scene_id2name prepared_data/scene36_64_id2name_top10.json \
--scene_feat_path forking_paths_dataset/next_x_v1_dataset_prepared_data/obs_data/scene_seg/ \
--scene_h 36 --scene_w 64 --scene_conv_kernel 3 --scene_conv_dim 64 \
--grid_strides 2,4 --use_grids 1,0 --num_out 20 --diverse_beam \
--diverse_gamma 0.01 --fix_num_timestep 1 --gpuid 0
```

**Comment by JunweiLiang** [comment]
It should be consistent, otherwise the model weights and graph would be mismatched. Do you get a different result if adding `--use_gnn`? I could be hard-coded it somewhere due to laziness.

**Comment by HRHLALALA** [comment]
> It should be consistent, otherwise the model weights and graph would be mismatched. Do you get a different result if adding `--use_gnn`? I could be hard-coded it somewhere due to laziness.

Hi, no apparent difference but when I add tf.Print in the use_GNN part, no message shows, while i can see it if I add "--use_gnn".

**Comment by JunweiLiang** [comment]
Could be due to the design of the beam search. Will take a closer look this weekend

**Comment by HRHLALALA** [comment]
> Could be due to the design of the beam search. Will take a closer look this weekend

Hi Junwei, thanks for your reply.

I have also added some printing information:
![image](https://user-images.githubusercontent.com/32263355/178554345-4da118f6-9ab8-47b7-8928-406d4448ec93.png)
It seems that the model will skip this part if no `--use_gnn`

```
# no --use_gnn
pre[[[[-0.86425817 -0.962910533 -0.0758371204...]]]...]
post[[[[-0.86425817 -0.962910533 -0.0758371204...]]]...]
pre[[[[-0.850579202 -0.958503 -0.0930521488...]]]...]
post[[[[-0.850579202 -0.958503 -0.0930521488...]]]...]
pre[[[[-0.837365031 -0.953913808 -0.101791024...]]]...]
post[[[[-0.837365031 -0.953913808 -0.101791024...]]]...]
```
```
# --use_gnn
pre[[[[-0.278288722 -0.295239747 -0.835967124...]]]...]
post[[[[-0.640386462 -0.411536157 -1.47378743...]]]...]
pre[[[[-0.436588734 -0.44524017 -0.849666655...]]]...]
post[[[[-0.906123 -0.62592864 -1.61872959...]]]...]
pre[[[[-0.579759777 -0.578057826 -0.843448222...]]]...]
post[[[[-1.16338181 -0.820196688 -1.68903947...]]]...]
```
Hope this can help your further analysis. Looking forward to your further results.

**Comment by JunweiLiang** [comment]
Hi, I have tested the code with and without `--use_gnn`. The conclusion is that it should be used with `--use_gnn` since it is trained that way and I have updated the instructions. You could try training and testing without GNN to see its effect. The small difference in performance is a surprise but the code is a bit messy to dive deep into. I'm planning to move to the latest PyTorch on this.

<table>
  <tr>
   <td></td>
    <td>45-degree-ADE</td>
    <td>top-down-ADE</td>
    <td>45-degree-FDE</td>
    <td>top-down-FDE</td>
  </tr>
  <tr>
   <td>with GNN</td>
    <td>170.03</td>
    <td>158.91</td>
    <td>336.28</td>
    <td>318.41</td>
  </tr>
<tr>
   <td>without GNN</td>
    <td>170.84</td>
    <td>158.49</td>
    <td>337.49</td>
    <td>320.07</td>
  </tr>
</table>
(They don't quite the same as what was reported before. Not sure why. Could be due to some numerical issues of different version of packages)

**Comment by HRHLALALA** [comment]
Hi

> Hi, I have tested the code with and without `--use_gnn`. The conclusion is that it should be used with `--use_gnn` since it is trained that way and I have updated the instructions. You could try training and testing without GNN to see its effect. The small difference in performance is a surprise but the code is a bit messy to dive deep into. I'm planning to move to the latest PyTorch on this.
> 
> 45-degree-ADE	top-down-ADE	45-degree-FDE	top-down-FDE
> with GNN	170.03	158.91	336.28	318.41
> without GNN	170.84	158.49	337.49	320.07
> (They aren't quite the same as what was reported before. Not sure why. Could be due to some numerical issues of different versions of packages)

Hi, thanks for your reply. I have tried and no apparent difference. I have had a deeper exploration of this model and find that the performance is very limited using this part. I am currently trying to diagnose this part and hope to get more innovations.

BTW, I have reimplemented next-prediction using PyTorch. You can look at [here](https://github.com/HRHLALALA/next-prediction-pytorch) if you are interested in it.

**Comment by JunweiLiang** [comment]
> BTW, I have reimplemented next-prediction using PyTorch. You can look at [here](https://github.com/HRHLALALA/next-prediction-pytorch) if you are interested in it. Note that the model is not fully tested and there might be some bugs inside since the performance is not as good as on TF.

Wow! This is awesome. Do you have a personal page that I could reference? I'll put a link to your repo in the Google repo descriptions. Though It is strange PyTorch impl would suffer a slight performance difference if the training recipe is the same. Closing this issue for now.
