### ISSUE TITLE
Prepare training data?

### ISSUE THREAD

**Issue by 108618026** [JunweiLiang/Multiverse#38]
Hello @JunweiLiang 
I would like to confirm that the **data**(sddactev_trainval/actev/) use to finetune SimAug model is the **same** as the outcomes of following your preprocessing rules in training??

1. Get data split
2. Get trajectories
3. Get RGB frames and scene segmentation features
4. Remove videos with bad trajectories
5. Preprocess data into npz files for efficient training

```
python code/train.py sddactev_trainval/actev/ simaug_my_finetune actev_modelname \
 --load_from packed_models/best_simaug_model/00/best/ --wd 0.001 --runId 0 \
 --obs_len 8 --pred_len 12 --emb_size 32 --enc_hidden_size 256 --dec_hidden_size \
 256 --activation_func tanh --keep_prob 1.0 --num_epochs 30 --batch_size 20 \
 --init_lr 0.05 --use_gnn --learning_rate_decay 0.95 --num_epoch_per_decay 2.0 \
 --grid_loss_weight 1.0 --grid_reg_loss_weight 0.1 --save_period 1000 --scene_h 36 \
 --scene_w 64 --scene_conv_kernel 3 --scene_conv_dim 64 --scene_grid_strides 2,4 \
 --use_grids 1,0 --val_grid_num 0 --train_w_onehot --gpuid 0
```

Another question is that I would like to use the Argoverse dataset to finetune the SimAug model, whether it's possible to use three-view samples for training(e.g. front-center, front-left, front-right)??

Thanks in advance!

**Comment by JunweiLiang** [comment]
Yes the pre-processed data downloaded from the [testing instructions](https://github.com/JunweiLiang/Multiverse/blob/master/SimAug/TESTING.md) should be the same from the [preprocessing instructions](https://github.com/JunweiLiang/Multiverse/blob/master/SimAug/PREPRO.md).
You can also check out this [fork](https://github.com/JunweiLiang/next-prediction/tree/master/code/prepare_data) from the Google-Next-Prediction.

> Another question is that I would like to use the Argoverse dataset to finetune the SimAug model, whether it's possible to use three-view samples for training(e.g. front-center, front-left, front-right)??
Yes! It should work as long as they have overlapping and synchronized views.
