### ISSUE TITLE
The project website does not open

### ISSUE THREAD

**Issue by ligadou1996** [JunweiLiang/Multiverse#39]
Hello, your URL: https://next.cs.cmu.edu/multiverse/ can't be opened, there are a lot of data that can't be downloaded, can you upload to GIT?

**Comment by JunweiLiang** [comment]
CMU may have decommissioned the servers. I will deal with it when I have time. STOP message-bombing me.

**Comment by JunweiLiang** [comment]
You can try to replace all URLs' `https://next.cs.cmu.edu/` with `http://precognition.team/next/` to download the data. I'll update the links on Github soon

**Comment by ligadou1996** [comment]
Thank you so much!



---Original---
From: "Junwei ***@***.***&gt;
Date: Sat, Nov 12, 2022 14:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [JunweiLiang/Multiverse] The project website does not open (Issue#39)




 
You can try to replace all URLs' https://next.cs.cmu.edu/ with http://precognition.team/next/ to download the data. I'll update the links on Github soon

**Comment by Decayyyy** [comment]
Hello, is the data available now?

**Comment by ligadou1996** [comment]
yes!Thank you so much!



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 12, 2022 15:55 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [JunweiLiang/Multiverse] The project website does not open (Issue#39)




 
Hello, is the data available now?

**Comment by JunweiLiang** [comment]
I'm asking around to restore the data onto a new server. Currently only data from the Next-prediction is on the precognition website

**Comment by JiyouSeo** [comment]
Hello, @JunweiLiang 
Where can I download the data?
I cannot download from the URL to 'https://precognition.team/next/data/072019_prepare_data/072019_next_my_prepare_nopersoncnn.tgz' yet

**Comment by JunweiLiang** [comment]
This part is missing from my backups. I'm contacting CMU to restore the data. Please be patient or ask others that have downloaded the data before. Thanks.

**Comment by Lesballes** [comment]
> Thank you so much!
> […](#)
> ---Original--- From: "Junwei ***@***.***&gt; Date: Sat, Nov 12, 2022 14:31 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [JunweiLiang/Multiverse] The project website does not open (Issue#39) You can try to replace all URLs' https://next.cs.cmu.edu/ with http://precognition.team/next/ to download the data. I'll update the links on Github soon — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

@ligadou1996 I am intrested to this work, but i found something wrong to get the data. Would you mind to send me this data via 919806472@qq.com or via anything you like?

**Comment by JunweiLiang** [comment]
I have recovered the data and they will be uploaded to the precognition.team/next in a few days.

**Comment by JunweiLiang** [comment]
@JiyouSeo You should be able to download `https://precognition.team/next/data/072019_prepare_data/072019_next_my_prepare_nopersoncnn.tgz` now.

**Comment by JiyouSeo** [comment]
Thank you for your kindly help!!

**Comment by JunweiLiang** [comment]
All the URLs have been fixed by moving to our HKUST Precognition Lab server. Closing this now.
