### ISSUE TITLE
No such file or directory: 0000_11_346_cam2.p

### ISSUE THREAD

**Issue by isaryo** [JunweiLiang/Multiverse#4]
Hi.
I try Visualize the Dataset.
So I have a problem.
FileNotFoundError: [Errno 2] No such file or directory: 'next_x_v1_dataset_prepared_data/multifuture/test/0000_11_346_cam2.p'
Do you have a solution?

**Comment by JunweiLiang** [comment]
It is probably due to errors occurred in previous steps. Please provide all the outputs from running the commands in [preparing the data](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#prepare-data).

**Comment by isaryo** [comment]
There's so much to tell you, I can't write it here.
Please check [this](https://docs.google.com/document/d/1LCfCLsJ0wZ9OSSsyZIqur6PIYkquyZEFIVuLFSJwjhQ/edit?usp=sharing) out.
This is google documents.

**Comment by JunweiLiang** [comment]
Try removing 0000_11_346_cam2.mp4 and then run the visualization command again.
```
$ rm next_x_v1_dataset/rgb_videos/0000_11_346_cam2.mp4
```

**Comment by isaryo** [comment]
I get the same error.
Traceback (most recent call last):
  File "code/visualize_multifuture_dataset.py", line 74, in <module>
    with open(os.path.join(args.gt_path, "%s.p" % traj_id), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'next_x_v1_dataset_prepared_data/multifuture/test/0000_11_346_cam2.p'

**Comment by JunweiLiang** [comment]
I have added a check for the pickle files. Now it should ignore that video.
