### ISSUE TITLE
Additional material for simaug article

### ISSUE THREAD

**Issue by CAOXINGWEN** [JunweiLiang/Multiverse#40]
Hello author, I want a copy of the supplemental material for the simaug article, the supplemental material I downloaded from the eccv website shows the zip archive is corrupted，thanks

**Comment by ligadou1996** [comment]
Can you go to his project website？

**Comment by ligadou1996** [comment]
Thank you, sorry to bother you, I rarely use foreign social software, I thought you use less frequency.



---Original---
From: "Junwei ***@***.***&gt;
Date: Fri, Nov 11, 2022 10:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JunweiLiang/Multiverse] Additional material for simaug article(Issue #40)




 
@CAOXINGWEN There is no other material. The zip is probably the code, which I have released in this repo.
