### ISSUE TITLE
pygame Windows图像无法呈现

### ISSUE THREAD

**Issue by nss6planner** [JunweiLiang/Multiverse#42]
您好，
   我在根据您的步骤一步步运行时出现了pygame窗口没有图像生成，而且在运行您给出的软件包的example也出现同样的问题。请问这是为什么，怎么解决
![image](https://user-images.githubusercontent.com/119504409/226178275-1a73bc17-b589-41ed-b997-55137580d7f1.png)
![image](https://user-images.githubusercontent.com/119504409/226178285-7705c30e-45d6-4ba7-931d-a8aa07681bbd.png)

**Comment by JunweiLiang** [comment]
可以先看pygame或者server端报错信息是什么
