### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by nss6planner** [JunweiLiang/Multiverse#43]
Hello, I'm running Multi-Future Trajectory Prediction and when I execute the first python command I get the following error, the error says the file doesn't exist, then I searched the whole folder package and didn't find the file, how can I solve this problem, I'm very much looking forward to getting your answer.
The error message is as follows:
(tens) air-nss@airnss-Legion-R9000P-ARX8:~/predict/Multiverse$ python code/multifuture_inference.py forking_paths_dataset/next_x_v1_dataset_prepared_data/obs_data/traj_2.5fps/test/ \
> forking_paths_dataset/next_x_v1_dataset_prepared_data/multifuture/test/ \
> multiverse-models/multiverse_single18.51_multi168.9_nll2.6/00/best/ \
> model1_output.traj.p --save_prob_file model1_output.prob.p \
> --obs_len 8 --emb_size 32 --enc_hidden_size 256 --dec_hidden_size 256 \
> --use_scene_enc --scene_id2name prepared_data/scene36_64_id2name_top10.json \
> --scene_feat_path forking_paths_dataset/next_x_v1_dataset_prepared_data/obs_data/scene_seg/ \
> --scene_h 36 --scene_w 64 --scene_conv_kernel 3 --scene_conv_dim 64 \
> --grid_strides 2,4 --use_grids 1,0 --num_out 20 --diverse_beam --use_gnn \
> --diverse_gamma 0.01 --fix_num_timestep 1 --gpuid 0
Traceback (most recent call last):
  File "code/multifuture_inference.py", line 407, in <module>
    inputs = get_inputs(args, traj_files, gt_trajs)
  File "code/multifuture_inference.py", line 170, in get_inputs
    with open(args.scene_id2name, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'prepared_data/scene36_64_id2name_top10.json'

**Comment by JunweiLiang** [comment]
From here: https://github.com/JunweiLiang/next-prediction/blob/master/code/prepare_data/README.md#preprocess
