### ISSUE TITLE
error in preprocessing of data for testing trained modal

### ISSUE THREAD

**Issue by wasif2mehmood** [JunweiLiang/Multiverse#44]
**when i run step 1 preprocess code command i get below error please guide**

Warning - Keypoint Feature: VIRAT_S_000201_08_001652_001838 5580_7 not exists
Warning - Appearance Feature: VIRAT_S_000201_08_001652_001838 VIRAT_S_000201_08_001652_001838_5580_7 not exists
100%|###################################################################################################################| 56/56 [01:31<00:00,  1.64s/it] 
total frames 15214, seq_list shape:(50233, 20, 2), total unique frame used:16681
total unique person box:58647
Traceback (most recent call last):
  File "C:\Users\A.C\Desktop\Multiverse-master\code\preprocess.py", line 911, in <module>
    main(arguments)
  File "C:\Users\A.C\Desktop\Multiverse-master\code\preprocess.py", line 139, in main
    prepro_each(args.traj_path, "train", os.path.join(
  File "C:\Users\A.C\Desktop\Multiverse-master\code\preprocess.py", line 716, in prepro_each
    other_box_seq_list = np.asarray(
                         ^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (50233, 20) + inhomogeneous part.

**Comment by zcc2333** [comment]
same, have you solved this problem?

**Comment by zcc2333** [comment]
I think it is because the numpy version is not correct.
