### ISSUE TITLE
How to implement on a custom video?

### ISSUE THREAD

**Issue by Mzunoven** [JunweiLiang/Multiverse#6]
Thanks for your great work.

Currently I want to do a single future prediction on a custom video, so I want to ask how to implement this network on a real-world video? Can you give some instructions on how to prepare my video and do prediction?

Thanks!

**Comment by JunweiLiang** [comment]
As mentioned in the [README](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#prepare-data), Multiverse follows [Next-prediction](https://next.cs.cmu.edu/index.html) data preparation protocol, so you call follow instructions from [here](https://github.com/google/next-prediction#preparing-rich-visual-features) for custom datasets. For inferencing on a single video, I don't plan to prepare code for Multiverse, but you can refer to this [repo](https://github.com/JunweiLiang/social-distancing-prediction) which uses Next-prediction models.
