### ISSUE TITLE
How to create a new dataset for some videos.

### ISSUE THREAD

**Issue by isaryo** [JunweiLiang/Multiverse#7]
Hi.
I want to know how to create a new forking path dataset for other datasets.
Then, what do I need data source? 
For example, Is it difficult without homography matrics of the video?

**Comment by JunweiLiang** [comment]
All instructions for creating a new dataset are already in the [README](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset). Without homography matrics, you won't be able to automatically reconstruct trajectories onto the ground plane.
