### ISSUE TITLE
SDD and Argoverse npz train and validation files.

### ISSUE THREAD

**Issue by jagmonroy** [JunweiLiang/Multiverse#9]
Hi,

congratulations, great work you have here. I wonder if it is possible sharing the datasets you used in SimAug to train in the same way as you did in Next Prediction. In NextP repo it is possible download a train, val and test npz files for Actev dataset. Is there something similar available for SDD and Argoverse Dataset? I only found the test npz files for SDD and Argoverse. 

thanks a lot in advance.

**Comment by JunweiLiang** [comment]
Thanks. I will do that in a week. Note that for SimAug training we do not use training data from real videos (ActEV/SDD/Argoverse), only in the fine-tuning experiments.

**Comment by JunweiLiang** [comment]
I finally have time to do this. The train/val npz files for SDD are shared [here](https://github.com/JunweiLiang/Multiverse/blob/master/SimAug/TRAINING.md#finetuning-on-sddactev). You can also follow instructions from [here](https://github.com/JunweiLiang/Multiverse/blob/master/SimAug/PREPRO.md) to extract from the original dataset. For Argoverse, we did not do any fine-tuning so there is no train/val npz file shared. But you can easily do so based on the PROPRO instructions.
